### ISSUE TITLE
Moving a node fails

### ISSUE THREAD

**Issue by gaia** [skalenetwork/node-cli#202]
install validator & node cli on a new machine.
copy ~/.skale/node_data/ from the old machine to the new one
run `init` on the new machine.

```
$ skale node info
This SKALE node is not registered on SKALE Manager yet
```

PS: sgx wallet is on a separate machine in the LAN. on the old machine, `skale wallet info` brought up `0x2a2f368c8e6d269d3f87bda4e9d1d10640f7e8b7`. on the new one, it brings `0x08f8ed68b60da3d1db08645f920d5cf57c759233`.  I don't see how a node can use a previous registration if sgx-wallet returns a different address.

**Comment by cstrangedk** [comment]
Failure resulted because backup feature was not yet implemented. Closes #219
