### ISSUE TITLE
IPtables manager uses /etc/services port definitions to keep SSH open when SSH is not running on 22

### ISSUE THREAD

**Issue by gaia** [skalenetwork/node-cli#531]
it would be VERY helpful if the component managing iptables used /etc/services to look for which port to keep open for SSH, instead of assuming 22. we don't use standard SSH ports and thus we have to resort to cron every 5 minutes making sure that the alternate port is open.

We audit using lynis: https://github.com/CISOfy/lynis/issues/604#issuecomment-442460364

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-4588)

**Comment by badrogger** [comment]
[2.1.3-beta.0](https://github.com/skalenetwork/node-cli/releases/tag/2.1.3-beta.0)

**Comment by badrogger** [comment]
Test:
1. Change sshd port on your server (https://linuxconfig.org/how-to-change-ssh-port-on-linux).
2. Make sure you still have ssh access after node installation.

**Comment by OleksanderSalamatov** [comment]
Approved to be working on node-cli: 2.1.3-beta.0
Result in test case in Testrail C906
