### ISSUE TITLE
Node cli docker-compose check fails if there are any warnings

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/node-cli#589]
Describe the bug
If anything present stderr in docker-compose -v output compliance check will be failed. It can corrupt init and upgrade procedures for validators. We need to make sure we parsing only stdout output.

To Reproduce

Download node-cli on Ubuntu 18.04 machine with AWS
Run skale node init
Expected behavior
docker-compose check should return ok

**Comment by OleksanderSalamatov** [comment]
Verified
Node-cli: 2.1.0-beta.2
Init working correctly (docker-compose check takes only stdout output and ignores stderr)

**Comment by badrogger** [comment]
[2.2.0-beta.1](https://github.com/skalenetwork/node-cli/releases/tag/2.2.0-beta.1)

**Comment by OleksanderSalamatov** [comment]
Approved to be working on node-cli: [2.2.0-beta.1](https://github.com/skalenetwork/node-cli/releases/tag/2.2.0-beta.1)
Detailed result in testrail test case C907
