### ISSUE TITLE
Command 'skale exit status' shows incorrect result output

### ISSUE THREAD

**Issue by alexgex** [skalenetwork/node-cli#622]
Command `skale exit status` shows incorrect result output if the node is in Maintenance mode

**Preconditions**
The node is in Maintenance mode

**To Reproduce**
Run commands:
`skale exit start`
`skale exit status`

**Expected behavior**
Output should be like "Node exiting is in process"

**Actual result**
Output is "Node exiting is completed"

**Versions**
node-cli: 2.1.0

**IMPORTANT!!!**
`skale exit start` shouldn't start AT ALL if the node is in Maintenance mode and the proper message should be shown

**Comment by badrogger** [comment]
admin: `2.3.4-develop.3` 
node-cli: `2.1.2`

**Comment by yatsunastya** [comment]
Checked with admin: `2.4.0-beta.1` and node-cli: `2.2.0-beta.1`

Node is Active

```
skale exit status

Schain name   Status
--------------------


Exiting is not started. Node is active
```


Node is in Maintenance

``` 
Command failed with following errors:
--------------------------------------------------
Node is in maintenance
```

**Comment by EvgeniyZZ** [comment]
Can't be tested without running node exit procedure

**Comment by badrogger** [comment]
[2.2.0-beta.1](https://github.com/skalenetwork/node-cli/releases/tag/2.2.0-beta.1)

**Comment by yatsunastya** [comment]
Node cli: 2.3.0-beta.0

In case of trying to run command `skale exit start` on Active node (skip contract step)
```
root@ns1000054:~# skale exit start
Are you sure you want to destroy your SKALE node? [y/N]: y
[2023-04-14 16:55:13,693 INFO] node_cli.cli.exit:55 - MainThread - Node exit process is started. Please, wait until exiting process will be completed
To check current state of exiting process try:

  skale exit status

Node exit process is started. Please, wait until exiting process will be completed
To check current state of exiting process try:

  skale exit status

```
