### ISSUE TITLE
Sync node: add option to enable/disable block rotation

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/node-cli#635]
For sync node CLI we should be able to enable/disable block rotation during node init/update:
- `.env` file or cli option could be used
- then the option should be saved somewhere and passed to sChain config

**Comment by gannakulikova** [comment]
**Can provide an option during a node installation**
   - enabled - Sync Node
   - disabled - Archive Node

**Comment by gannakulikova** [comment]
We should be able to move from Archive Node -> Sync Node, not a part of this release, should be scheduled for future Sync Node releases cc @cstrangedk @kladkogex
