### ISSUE TITLE
Chain containers may be untagged during update 

### ISSUE THREAD

**Issue by badrogger** [skalenetwork/node-cli#640]
With proper timing  upgrade procedure may start to remove image during container creation. We should avoid this.

**Comment by badrogger** [comment]
[2.1.2-beta.0 ](https://github.com/skalenetwork/node-cli/releases/tag/2.1.2-beta.0)

**Comment by oleksandrSydorenkoJ** [comment]
Steps to reproduce:
1. Change CONTAINER_CONFIGS_STREAM to another tag/branch
2. Run skale node update 
3. Check tags of images for skaled container

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network
node-cli: [2.1.2-beta.0](https://github.com/skalenetwork/node-cli/releases/tag/2.1.2-beta.0)

before
```
/dev/nvme0n1p1                                  97G   87G   11G  90% /
```

after
```
/dev/nvme0n1p1                                  97G   64G   34G  66% /
```
[prune_nodes.log](https://github.com/skalenetwork/node-cli/files/9353418/prune_nodes.log)
