### ISSUE TITLE
Add Telemetry support

### ISSUE THREAD

**Issue by avirajkhare00** [skalenetwork/node-cli#649]
Modern CLI collects anonymous data from users containing information like what kind of commands users are running on their machine and demographics. It does not have any private data. Telemetry is an essential feature for any CLI. You can work on what you can measure.

We can have the following functionalities:
 - Enable Telemetry support in the CLI
 - Push the telemetry data on Google Analytics to give you a real-time overview of CLI usage.
 Please refer to this doc: https://cloud.google.com/service-infrastructure/docs/telemetry-reporting
 - Consume the data from GA to Grafana, and produce meaningful graphs.

**Comment by dmytrotkk** [comment]
I'm not sure that it makes sense for us to collect any user data from our CLI tools, closing
