### ISSUE TITLE
Ubuntu 20.04 support

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/node-cli#710]
* PRD: SYSTEM UPGRADE

We need to make node cli binary work with both old and new libc. Binary should contain all the dependencies to work well in both Ubuntu 18.04 and Ubuntu 20.04 version.

**Comment by OleksanderSalamatov** [comment]
Verified
Node-cli: 2.3.0-beta.1
Ubuntu: 18.04, 20.04
Testrail: R184 in Skale Node project

2.1.1 node-cli is working correctly both on Ubuntu 18.04 and Ubuntu 20.04
