### ISSUE TITLE
Add the OS version check for Watchdog API

### ISSUE THREAD

**Issue by alexgex** [skalenetwork/node-cli#722]
- PRD: SYSTEM UPGRADE

We need to have a possibility to check the OS name/version of the SKALE node. The existing `status/hardware` API call should return, among other things, the OS name and version of the host.

**Comment by DmytroNazarenko** [comment]
Decided to move check to `status/meta-info`

**Comment by DmytroNazarenko** [comment]
Check moved to `status/meta-info` API call

**Comment by OleksanderSalamatov** [comment]
Verified
Skale-admin: 2.4.0
Node-cli: 2.3.0-beta.1
Watchdog: 2.1.1-stable.1
Ubuntu: 18.04, 20.04
Testrail: C1000 in skale-node project

```
➜  ~ curl http://x.x.x.x:3009/status/meta-info
{"data": {"version": "2.3.0-beta.1", "config_stream": "regression-2.1.16", "docker_lvmpy_stream": "1.0.3-beta.0", "os_id": "ubuntu", "os_version": "20.04"}, "error": null}
➜  ~ curl http://y.y.y.y:3009/status/meta-info
{"data": {"version": "2.3.0-beta.1", "config_stream": "regression-2.1.16", "docker_lvmpy_stream": "1.0.3-beta.0", "os_id": "ubuntu", "os_version": "18.04"}, "error": null}
```
