### ISSUE TITLE
Update OS version info during the execution of "skale node turn-on" command

### ISSUE THREAD

**Issue by alexgex** [skalenetwork/node-cli#744]
For now the OS version is updated in `meta-info` data during `skale node update` procedure only. If a validator upgrades Ubuntu version  without the following node updating, the OS version info remains old. The external "OS version check" will be incorrect in this case. 
So, `meta-info` data should be also updated during the execution of the command `skale node turn-on`.

node-cli version: 2.3.0

**Comment by OleksanderSalamatov** [comment]
Do not work

Updated `Ubuntu 20.04` to `Ubuntu 22.04` on exited node on Regression network
`/etc/lsb-release` changed, but in watchdog `os_version` check is still `20.04`

Additional `turn-off`s and `turn-on`s do not resolve problem
Node reboots do not resolve the problem

**Comment by OleksanderSalamatov** [comment]
Verified

node-cli: `2.5.0-beta.0`

After `turn-on` meta-info is updated and new node-cli and Ubuntu version show up

`{"data": {"version": "2.5.0-beta.0", "config_stream": "regression-3.1-initial", "docker_lvmpy_stream": "1.0.2-stable.0", "os_id": "ubuntu", "os_version": "22.04"}, "error": null}`
