### ISSUE TITLE
Block skale node update during node rotation

### ISSUE THREAD

**Issue by badrogger** [skalenetwork/node-cli#780]
To prevent issues caused by upgrading while node rotation is in progress we need add restriction that disallow running `skale node update` until rotation has been finished.

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Versions:
admin - `2.8.0-beta.0`
node-cli - `2.5.0-beta.0`

Skale node update failed during DKG and rotation delay
```
root@Regression-7:~# skale node update --yes init-env

2024-10-24 16:42:39,481 - INFO - Locked schains: ['skale-brown-gripping-tania-borealis']
Command failed with following errors:
--------------------------------------------------
Cannot update safely
--------------------------------------------------
You can find more info in /root/.skale/.skale-cli-log/debug-node-cli.log
```
